let root=null,currentPath=null,expanded=new Set(),loadingJob=null,selected=new Set(),reserved=new Map(),lastSelectedPath=null,pendingShift=false,viewMode='tree';const api=()=>window.pywebview.api;const $=id=>document.getElementById(id);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const jsarg=s=>JSON.stringify(String(s)).replace(/&/g,'\\u0026').replace(/'/g,'\\u0027').replace(/</g,'\\u003c');
function debugLog(message,data){const stamp=new Date().toISOString();if(data===undefined)console.log(`[Macacolandia ${stamp}] ${message}`);else console.log(`[Macacolandia ${stamp}] ${message}`,data)}
function setStatus(text,error=false){debugLog(error?'ERRO: '+text:'STATUS: '+text);$('status').textContent=text;$('status').classList.remove('hidden');$('status').classList.toggle('error',error)}
function clearStatus(){$('status').classList.add('hidden')}
function updateSelectedText(){$('selectedText').textContent=`${selected.size} selecionado${selected.size===1?'':'s'}`}
function setViewMode(mode){viewMode=mode==='cubes'?'cubes':'tree';$('viewTree').classList.toggle('active',viewMode==='tree');$('viewCubes').classList.toggle('active',viewMode==='cubes');$('treeHead').classList.toggle('hidden',viewMode!=='tree');render()}
async function loadDrives(){$('drives').innerHTML='<div class="drive-loading"><span class="loader mini"></span><span>Procurando os HDs…<small>Macacolandia está olhando</small></span></div>';try{const response=await api().start_drive_scan();pollDrives(response.job_id)}catch(e){driveError('Não consegui procurar os HDs.')}}
function pollDrives(jobId){setTimeout(async()=>{try{const job=await api().get_job(jobId);if(job.status==='done'){const drives=job.result||[];$('drives').innerHTML=drives.length?drives.map(d=>`<button class="drive" onclick='selectDrive(${jsarg(d)},this)'><span>▣</span><span><b>${esc(d)}</b><small>HD encontrado · clique para abrir</small></span></button>`).join(''):'<div class="drive-loading">Nenhum HD encontrado.<small>Tente escolher uma pasta.</small></div>'}else if(job.status==='error'){driveError('A busca pelos HDs deu ruim.')}else pollDrives(jobId)}catch(e){driveError('A busca pelos HDs deu ruim.')}},180)}
function driveError(text){$('drives').innerHTML=`<div class="drive-error">${esc(text)}<button onclick="loadDrives()">↻ Tentar de novo</button></div>`}
function selectDrive(path,button){document.querySelectorAll('.drive').forEach(x=>x.classList.remove('active'));button?.classList.add('active');loadDiskInfo(path);startScan(path)}
async function loadDiskInfo(path){$('diskInfo').innerHTML='<span class="loader mini"></span><small>Medindo o HD…</small>';try{const info=await api().get_disk_info(path);if(info.error){$('diskInfo').innerHTML=`<small>${esc(info.error)}</small>`;return}$('diskInfo').innerHTML=`<div class="disk-name">${esc(path)}</div><div class="banana-status">${info.bananas} <b>${esc(info.status)}</b></div><div class="disk-grid"><span><b>${info.total}</b><small>Total</small></span><span><b>${info.used}</b><small>Ocupado</small></span><span><b>${info.free}</b><small>Livre</small></span></div><div class="disk-bar"><i style="width:${info.used_percent}%"></i></div><small>${info.used_percent}% usado</small>`}catch(e){$('diskInfo').innerHTML='<small>Não consegui medir este HD.</small>'}}
async function startScan(path){loadingJob=null;root=null;currentPath=path;expanded.clear();selected.clear();lastSelectedPath=null;updateSelectedText();$('tree').innerHTML='<div class="empty loading"><div class="loader"></div><b>Preparando a leitura…</b><span>Calculando o peso das pastas sem abrir toda a árvore.</span></div>';setStatus('Análise em segundo plano iniciada — a janela continua respondendo.');try{const response=await api().start_scan(path);if(response.error){setStatus(response.error,true);return}poll(response.job_id,'root')}catch(e){setStatus('Não foi possível iniciar a análise: '+e,true)}}
function poll(jobId,kind,path){loadingJob=jobId;const tick=async()=>{if(loadingJob!==jobId)return;try{const job=await api().get_job(jobId);if(job.status==='done'){loadingJob=null;if(kind==='root')finishRoot(job.result);else finishChildren(path,job.result);return}if(job.status==='error'){loadingJob=null;setStatus(job.error||'Falha durante a leitura.',true);return}setTimeout(tick,180)}catch(e){loadingJob=null;setStatus('Erro consultando a análise.',true)}};tick()}
function finishRoot(result){const children=result?.children||[];const total=children.reduce((s,x)=>s+x.size_bytes,0);root={name:currentPath.split(/[\\/]/).filter(Boolean).pop()||currentPath,path:currentPath,type:'folder',size_bytes:total,size:formatBytes(total),children,loaded:true,scanned_at:new Date().toISOString()};expanded.add(root.path);updateHeader();render();clearStatus()}
function finishChildren(path,result){const node=findNode(root,path);if(node){node.children=result?.children||[];node.loaded=true;expanded.add(path)}render();clearStatus()}
function findNode(node,path){if(!node)return null;if(node.path===path)return node;for(const child of node.children||[]){const found=findNode(child,path);if(found)return found}return null}
function formatBytes(n){let v=Number(n),unit='B';for(const u of ['B','KB','MB','GB','TB','PB']){unit=u;if(v<1024)break;v/=1024}return `${v.toFixed(1)} ${unit}`}
function updateHeader(){const children=root.children||[],files=children.filter(x=>x.type==='file'),folders=children.filter(x=>x.type==='folder'),biggest=children[0],lightest=children[children.length-1],types=[...new Set(files.map(x=>x.kind||'outro'))];$('rootName').textContent=root.name;$('treeTitle').textContent=root.name;$('currentPath').textContent=root.path;$('total').textContent=root.size;$('count').textContent=children.length;$('largest').textContent=biggest?.name||'—';$('heaviest').textContent=biggest?.name||'—';$('heavyText').textContent=biggest?`${biggest.size} — pesa mais que os outros`:'Nenhum item ainda';$('lightest').textContent=lightest?.name||'—';$('lightText').textContent=lightest?`${lightest.size} — é o menor da lista`:'Nenhum item ainda';$('fileTypes').textContent=types.length?types.length+' tipos diferentes':'—';$('typeText').textContent=types.length?types.join(', '):'Ainda não há arquivos';$('emptyFolders').textContent=folders.filter(x=>x.size_bytes===0).length;$('scanInfo').textContent='Leitura concluída · '+new Date().toLocaleTimeString()}
function iconFor(node){return node.type==='folder'?'▱':node.kind==='vídeo'?'▶':node.kind==='imagem'?'▧':node.kind==='áudio'?'♫':'▤'}
function visibleNodes(){const list=[];const visit=node=>{if(!node)return;list.push(node);if(node.type==='folder'&&expanded.has(node.path)&&node.loaded)(node.children||[]).forEach(visit)};visit(root);return list}
function applyRange(path,checked=true){const nodes=visibleNodes(),target=nodes.findIndex(node=>node.path===path),anchor=nodes.findIndex(node=>node.path===lastSelectedPath);if(target<0){if(checked)selected.add(path);else selected.delete(path);return}if(anchor<0){if(checked)selected.add(path);else selected.delete(path);return}const start=Math.min(target,anchor),end=Math.max(target,anchor);for(let i=start;i<=end;i++){if(checked)selected.add(nodes[i].path);else selected.delete(nodes[i].path)}}
function checkboxMouseDown(event,path){pendingShift=event.shiftKey;event.stopPropagation()}
function selectItem(event,path){const checked=!!event.target.checked;if(pendingShift||event.shiftKey)applyRange(path,checked);else if(checked)selected.add(path);else selected.delete(path);pendingShift=false;lastSelectedPath=path;updateSelectedText();render()}
function selectRow(event,path){if(event.shiftKey){applyRange(path,true);lastSelectedPath=path;updateSelectedText();render();return false}return true}
function rowActivate(event,path){if(!selectRow(event,path))return;previewFile(path)}
function folderActivate(event,path){event.stopPropagation();if(event.shiftKey)applyRange(path,true);else selected.add(path);lastSelectedPath=path;updateSelectedText();render()}
function row(node,depth,total){const has=node.type==='folder',open=expanded.has(node.path),pct=total?node.size_bytes/total*100:0,checked=selected.has(node.path)?'checked':'',risk=node.possible_risk?' risk':'',empty=node.type==='folder'&&node.size_bytes===0?' empty-folder':'',path=jsarg(node.path);return `<div class="tree-row ${selected.has(node.path)?'selected':''}${risk}${empty}" style="padding-left:${19+depth*22}px" draggable="true" ondragstart='startDrag(event,${path})' ondragover="${has?'event.preventDefault();this.classList.add(\'drag-over\')':''}" ondragleave="${has?"this.classList.remove('drag-over')":''}" ondrop='${has?`dropOnFolder(event,${path})`:''}' onclick='${has?`folderActivate(event,${path})`:`rowActivate(event,${path})`}'><span class="tree-name"><input class="check" type="checkbox" ${checked} onmousedown='checkboxMouseDown(event,${path})' onclick="event.stopPropagation()" onchange='selectItem(event,${path})'><span class="toggle" ${has?`onclick='event.stopPropagation();toggle(event,${path})'`:''}>${has?(open?'▾':'▸'):''}</span><span class="folder">${iconFor(node)}</span><b>${esc(node.name)}</b>${node.possible_risk?`<span class="risk-badge">ATENÇÃO</span><button class="github-btn" onclick='event.stopPropagation();searchGithub(${path})'>GitHub</button>`:''}</span><span class="size">${esc(node.size)}</span><span class="usage"><span class="bar"><i style="width:${Math.max(pct,1)}%"></i></span><small>${pct.toFixed(1)}%</small></span><span class="path-cell">${esc(node.kind||'pasta')} · ${esc(node.path)}</span></div>${open&&has?(node.loaded?((node.children||[]).map(c=>row(c,depth+1,node.size_bytes)).join('')||'<div class="child-empty">Pasta vazia: não tem nada dentro</div>'):'<div class="child-loading" style="margin-left:'+(39+depth*22)+'px"><span class="loader mini"></span> Calculando conteúdo…</div>'):''}`}
function cubeVisual(node){if(node.type==='file'&&node.kind==='imagem'&&node.thumbnail_src)return `<img class="cube-thumb" src="${esc(node.thumbnail_src)}" alt="" loading="lazy" onerror="this.classList.add('thumb-failed');this.removeAttribute('src')">`;return `<div class="cube-icon">${iconFor(node)}</div>`}
function cubeNode(node,total){const has=node.type==='folder',open=expanded.has(node.path),pct=total?node.size_bytes/total*100:0,checked=selected.has(node.path)?'checked':'',risk=node.possible_risk?' risk':'',empty=node.type==='folder'&&node.size_bytes===0?' empty-folder':'',path=jsarg(node.path);let children='';if(open&&has)children=node.loaded?`<div class="cube-children">${(node.children||[]).length?(node.children||[]).map(child=>cubeNode(child,node.size_bytes)).join(''):'<div class="cube-empty">Pasta vazia: não tem nada dentro</div>'}</div>`:'<div class="cube-children"><div class="cube-loading"><span class="loader mini"></span> Calculando conteúdo…</div></div>';return `<div class="cube-card-wrap"><article class="cube-card${selected.has(node.path)?' selected':''}${risk}${empty}" draggable="true" ondragstart='startDrag(event,${path})' onclick='${has?`folderActivate(event,${path})`:`rowActivate(event,${path})`}'><input class="check" type="checkbox" ${checked} onmousedown='checkboxMouseDown(event,${path})' onclick="event.stopPropagation()" onchange='selectItem(event,${path})'>${cubeVisual(node)}<b class="cube-title" title="${esc(node.name)}">${esc(node.name)}</b><small class="cube-meta">${esc(node.size)} · ${esc(node.kind||'pasta')}</small><div class="cube-bar"><i style="width:${Math.max(pct,1)}%"></i></div>${has?`<span class="cube-open" onclick='event.stopPropagation();toggle(event,${path})'>${open?'▾':'▸'}</span>`:''}${node.possible_risk?'<span class="risk-badge">ATENÇÃO</span>':''}</article>${children}</div>`}
function renderCubes(){const children=root.children||[];$('tree').innerHTML=`<div class="cube-grid">${children.length?children.map(node=>cubeNode(node,root.size_bytes)).join(''):'<div class="empty">◫<b>Pasta vazia</b><span>Não há itens para mostrar nesta visão.</span></div>'}</div>`}
function render(){if(!root)return;if(viewMode==='cubes'){renderCubes();return}$('tree').innerHTML=row(root,0,root.size_bytes)}
async function toggle(e,path){e.stopPropagation();if(e.shiftKey){applyRange(path,true);lastSelectedPath=path;updateSelectedText();render();return}const node=findNode(root,path);if(!node||node.type!=='folder')return;if(expanded.has(path)){expanded.delete(path);render();return}expanded.add(path);if(!node.loaded){setStatus('Carregando os itens desta pasta…');try{const response=await api().expand_folder(path);if(response.error){setStatus(response.error,true);return}poll(response.job_id,'children',path)}catch(err){setStatus('Falha ao carregar a pasta.',true)}}render()}
function openNode(path){toggle({stopPropagation:()=>{},shiftKey:false},path)}
function findSelected(){return [...selected].map(path=>findNode(root,path)).filter(Boolean)}
async function loadReserved(){try{const result=await api().load_reserved();if(result.ok){reserved.clear();(result.items||[]).forEach(item=>reserved.set(item.path,item));renderReserved()}}catch(e){setStatus('Não foi possível carregar as reservas salvas.',true)}}
function persistReserved(){api().save_reserved([...reserved.values()]).then(result=>{if(!result.ok)setStatus(result.error||'Não foi possível salvar as reservas.',true)}).catch(()=>setStatus('Não foi possível salvar as reservas.',true))}
function renderReserved(){const list=$('reservedList');$('reservedCount').textContent=reserved.size;if(!reserved.size){list.innerHTML='<small>Nada reservado ainda</small>';return}list.innerHTML=[...reserved.values()].map(node=>`<div class="reserved-item ${node.type==='folder'?'reserved-folder':''}" draggable="true" ondragstart='startDrag(event,${jsarg(node.path)})' ${node.type==='folder'?`ondragover="event.preventDefault();this.classList.add('drag-over')" ondragleave="this.classList.remove('drag-over')" ondrop='dropOnReserved(event,${jsarg(node.path)})'`:''}><span>${node.type==='folder'?'▱':'▤'}</span><b title="${esc(node.path)}">${esc(node.name)}</b><button onclick='event.stopPropagation();removeReserved(${jsarg(node.path)})'>×</button></div>`).join('')}
function removeReserved(path){reserved.delete(path);renderReserved();persistReserved()}
function reserveSelected(){const nodes=findSelected();if(!nodes.length){setStatus('Marque pelo menos uma coisa primeiro.',true);return}nodes.forEach(node=>reserved.set(node.path,node));renderReserved();persistReserved();setStatus(`${nodes.length} coisa${nodes.length===1?'':'s'} guardada${nodes.length===1?'':'s'} no cantinho.`);selected.clear();lastSelectedPath=null;updateSelectedText();render()}
function clearReserved(){reserved.clear();renderReserved();persistReserved();setStatus('Cantinho limpo.')}
function startDrag(event,path){event.stopPropagation();event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',path)}
async function dropOnFolder(event,destination){event.preventDefault();event.stopPropagation();event.currentTarget.classList.remove('drag-over');const path=event.dataTransfer.getData('text/plain');if(!path||path===destination)return;await movePaths([path],destination)}
async function dropOnReserved(event,destination){event.preventDefault();event.stopPropagation();event.currentTarget.classList.remove('drag-over');const path=event.dataTransfer.getData('text/plain');if(!path||path===destination)return;await movePaths([path],destination)}
async function movePaths(paths,destination){if(!paths.length)return;if(!await askConfirmation('Mover itens',`Mover ${paths.length} item(ns) para esta pasta?`))return;debugLog('Iniciando movimento',{paths,destination});const response=await api().start_operation('move',paths,destination);debugLog('Resposta do movimento',response);if(response.error){setStatus(response.error,true);return}watchOperation(response.job_id,'Movendo coisas…')}
async function moveSelected(){const nodes=findSelected().concat([...reserved.values()]);const paths=[...new Set(nodes.map(n=>n.path))];if(!paths.length){setStatus('Marque ou reserve alguma coisa primeiro.',true);return}if(!await askConfirmation('Mover itens',`Mover ${paths.length} item(ns)? O Macacolandia vai pedir uma pasta de destino.`))return;const destination=await api().select_destination();if(!destination)return;const response=await api().start_operation('move',paths,destination);if(response.error){setStatus(response.error,true);return}watchOperation(response.job_id,'Movendo coisas…')}
async function deleteSelected(){const paths=[...new Set(findSelected().map(n=>n.path))];if(!paths.length){setStatus('Marque alguma coisa primeiro.',true);return}if(!await askConfirmation('Excluir itens',`Excluir ${paths.length} item(ns)? Isso apaga do computador e não vai para a lixeira.`,true))return;debugLog('Iniciando exclusão',paths);const response=await api().start_operation('delete',paths);debugLog('Resposta da exclusão',response);if(response.error){setStatus(response.error,true);return}watchOperation(response.job_id,'Apagando coisas…')}
let folderCreationParent=null
function createFolder(){if(!currentPath){setStatus('Escolha um HD ou pasta primeiro.',true);return}const folders=findSelected().filter(node=>node.type==='folder');folderCreationParent=folders.length===1?folders[0].path:currentPath;const selectedFolder=folders.length===1?folders[0].name:(root?.name||'esta pasta');$('folderModalText').textContent=`A nova subpasta será criada dentro de “${selectedFolder}”.`;$('folderName').value='';$('folderModal').classList.remove('hidden');setTimeout(()=>$('folderName').focus(),50)}
function closeFolderModal(){$('folderModal').classList.add('hidden');folderCreationParent=null}
async function submitCreateFolder(){const name=$('folderName').value.trim();if(!name){$('folderName').focus();setStatus('Digite um nome para a pasta.',true);return}const parent=folderCreationParent;if(!parent){closeFolderModal();return}try{const response=await api().create_folder(parent,name);if(!response.ok){setStatus(response.error||'Não foi possível criar a pasta.',true);return}closeFolderModal();const parentNode=findNode(root,parent);if(parentNode){const newNode={name:name,path:response.path,type:'folder',size_bytes:0,size:'0.0 B',kind:'pasta',mime:null,previewable:false,thumbnail_src:null,possible_risk:false,risk_reason:'',children:[],loaded:true};parentNode.children=parentNode.children||[];parentNode.children.push(newNode);parentNode.children.sort((a,b)=>b.size_bytes-a.size_bytes||a.name.localeCompare(b.name));parentNode.loaded=true;if(parentNode.type==='folder')expanded.add(parent);updateHeader();render()}selected.clear();lastSelectedPath=null;updateSelectedText();setStatus('Pasta criada com sucesso.')}catch(e){setStatus('Não foi possível criar a pasta.',true)}}
let confirmationResolver=null
function askConfirmation(title,text,danger=false){debugLog('Abrindo confirmação', {title,text});return new Promise(resolve=>{confirmationResolver=resolve;$('confirmModalTitle').textContent=title;$('confirmModalText').textContent=text;$('confirmModalOk').textContent=danger?'Excluir':'Confirmar';$('confirmModalOk').classList.toggle('danger',danger);$('confirmModal').classList.remove('hidden');setTimeout(()=>$('confirmModalOk').focus(),50)})}
function resolveConfirmation(value){debugLog('Confirmação respondida',value);$('confirmModal').classList.add('hidden');const resolver=confirmationResolver;confirmationResolver=null;if(resolver)resolver(value)}
function findParent(node,path){if(!node)return null;for(const child of node.children||[]){if(child.path===path)return node;const parent=findParent(child,path);if(parent)return parent}return null}
function rewriteNodePaths(node,oldPath,newPath){if(!node)return;node.path=newPath+node.path.slice(oldPath.length);(node.children||[]).forEach(child=>rewriteNodePaths(child,oldPath,newPath))}
function applyLocalDelete(result){(result?.items||[]).filter(item=>item.ok).forEach(item=>{const parent=findParent(root,item.path);if(parent?.children)parent.children=parent.children.filter(child=>child.path!==item.path);debugLog('Item removido visualmente',item.path)});updateHeader();render()}
function applyLocalMove(result){(result?.items||[]).filter(item=>item.ok&&item.destination).forEach(item=>{const source=findNode(root,item.path);if(!source)return;const sourceParent=findParent(root,item.path);if(sourceParent?.children)sourceParent.children=sourceParent.children.filter(child=>child.path!==item.path);const destinationPath=item.destination.replace(/[\\\\/][^\\\\/]*$/,"");const destination=findNode(root,destinationPath);if(destination&&destination.type==='folder'){rewriteNodePaths(source,item.path,item.destination);destination.children=destination.children||[];destination.children.push(source);destination.loaded=true;destination.children.sort((a,b)=>b.size_bytes-a.size_bytes||a.name.localeCompare(b.name))}});updateHeader();render()}
function watchOperation(jobId,label){setStatus(`${label} 0%`);const tick=async()=>{const job=await api().get_job(jobId);if(job.status==='done'){const failed=job.result?.failed||0;debugLog('Operação concluída',job.result);if(job.result?.items&&job.result.items.some(item=>item.destination))applyLocalMove(job.result);else if(job.result?.items)applyLocalDelete(job.result);selected.clear();reserved.clear();lastSelectedPath=null;renderReserved();persistReserved();updateSelectedText();setStatus(failed?`Terminou, mas ${failed} item(ns) deram problema.`:'Pronto! Operação terminou.');return}if(job.status==='error'){debugLog('Operação retornou erro',job);setStatus(job.error||'A operação deu ruim.',true);return}setStatus(`${label} ${job.progress||0}%`);setTimeout(tick,180)};tick()}
async function pickFolder(){try{const path=await api().select_folder();if(path){document.querySelectorAll('.drive').forEach(x=>x.classList.remove('active'));loadDiskInfo(path);startScan(path)}}catch(e){setStatus('Não foi possível abrir o seletor de pastas.',true)}}
async function scanCurrent(){if(currentPath)startScan(currentPath);else setStatus('Selecione um disco ou pasta primeiro.',true)}
async function searchGithub(path){const node=findNode(root,path);if(!node)return;api().open_github_search(node.name).then(result=>setStatus(result.message||'Busca aberta no GitHub.'))}
async function previewFile(path){const node=findNode(root,path);if(!node)return;try{const result=await api().get_preview(path);$('previewTitle').textContent=node.name;$('previewKind').textContent=(node.kind||'ARQUIVO').toUpperCase();if(!result.ok){$('previewBody').innerHTML=`<div class="preview-note">${esc(result.error)}<br><br>Você ainda pode exportar o JSON com as informações deste arquivo.</div>`}else if(result.kind==='imagem'){$('previewBody').innerHTML=`<img src="${result.src}" alt="${esc(node.name)}">`}else if(result.kind==='texto'){$('previewBody').innerHTML=`<pre class="text-preview"><code>${esc(result.text||'')}</code></pre>`}else if(result.kind==='vídeo'){$('previewBody').innerHTML=`<video src="${result.src}" controls autoplay></video>`}else{$('previewBody').innerHTML=`<audio src="${result.src}" controls></audio>`}$('preview').classList.remove('hidden')}catch(e){setStatus('Não consegui abrir a prévia.',true)}}
function closePreview(){$('preview').classList.add('hidden');$('previewBody').innerHTML=''}
let donationMethod='pix'
let donationCardForm=null
const MERCADO_PAGO_PUBLIC_KEY='APP_USR-967fd109-5686-427d-91ca-9f9e2a71268a'
function openDonation(){debugLog('Abrindo tela de doações');$('donationModal').classList.remove('hidden');setDonationMethod('pix')}
function closeDonation(){$('donationModal').classList.add('hidden');$('pixResult').classList.add('hidden');$('donationStatus').classList.add('hidden')}
function setDonationStatus(text,error=false){const box=$('donationStatus');box.textContent=text;box.classList.remove('hidden');box.classList.toggle('error',error);setStatus(text,error)}
function setDonationMethod(method){donationMethod=method==='card'?'card':'pix';$('donationPixTab').classList.toggle('active',donationMethod==='pix');$('donationCardTab').classList.toggle('active',donationMethod==='card');$('donationPixPanel').classList.toggle('hidden',donationMethod!=='pix');$('donationCardPanel').classList.toggle('hidden',donationMethod!=='card');if(donationMethod==='card')setTimeout(initDonationCardForm,50)}
async function generateDonationPix(){const amount=Number($('donationAmount').value);if(!amount||amount<1){setDonationStatus('Informe uma doação de pelo menos R$ 1,00.',true);return}setDonationStatus('Gerando QR Code Pix…');debugLog('Solicitando doação Pix',{amount});try{const result=await api().create_donation_pix(amount);debugLog('Resposta do Pix',result);if(!result.success){setDonationStatus(result.error||'Não foi possível gerar o Pix.',true);return}$('pixResult').innerHTML=`<img class="pix-qr" src="data:image/png;base64,${result.qr_code}" alt="QR Code Pix"><strong>Escaneie o QR Code ou copie o código Pix</strong><textarea readonly onclick="this.select()">${esc(result.qr_code_text||'')}</textarea><small>Pagamento ${esc(String(result.payment_id||''))} · R$ ${Number(result.valor||amount).toFixed(2)}</small>`;$('pixResult').classList.remove('hidden');setDonationStatus('QR Code Pix gerado com sucesso.')}catch(error){debugLog('ERRO Pix',error);setDonationStatus('Não foi possível comunicar com o servidor de pagamentos.',true)}}
function initDonationCardForm(){if(donationCardForm)return;if(typeof MercadoPago!=='function'){setDonationStatus('Não foi possível carregar os campos seguros do Mercado Pago.',true);return}try{const mp=new MercadoPago(MERCADO_PAGO_PUBLIC_KEY,{locale:'pt-BR'});donationCardForm=mp.cardForm({amount:String(Math.max(1,Number($('donationAmount').value)||1)),iframe:true,form:{id:'donation-card-form',cardNumber:{id:'donation-card-number',placeholder:'Número do cartão'},expirationDate:{id:'donation-card-expiration',placeholder:'MM/AA'},securityCode:{id:'donation-card-cvv',placeholder:'CVV'},cardholderName:{id:'donation-card-name',placeholder:'Nome completo'},issuer:{id:'donation-card-issuer',placeholder:'Banco emissor'},installments:{id:'donation-card-installments',placeholder:'Parcelas'},identificationType:{id:'donation-card-identification-type',placeholder:'Tipo de documento'},identificationNumber:{id:'donation-card-document',placeholder:'Número do documento'},cardholderEmail:{id:'donation-card-email',placeholder:'E-mail'}},callbacks:{onFormMounted:error=>{if(error)setDonationStatus('Não foi possível carregar os campos do cartão.',true)},onSubmit:event=>{event.preventDefault();submitDonationCard(donationCardForm.getCardFormData())}}})}catch(error){debugLog('ERRO ao iniciar cartão',error);setDonationStatus('Erro ao preparar o cartão.',true)}}
async function submitDonationCard(formData){const amount=Number($('donationAmount').value);const documentNumber=String(formData?.identificationNumber||'').replace(/\D/g,'');if(!amount||amount<1||!formData?.token||!formData?.paymentMethodId||!formData?.cardholderEmail||![11,14].includes(documentNumber.length)){setDonationStatus('Preencha número, validade, CVV, nome, e-mail e CPF/CNPJ.',true);return}setDonationStatus('Processando cartão com segurança…');debugLog('Solicitando doação com cartão',{amount,paymentMethod:formData.paymentMethodId});try{const result=await api().create_donation_card({amount,token:formData.token,issuer_id:formData.issuerId,payment_method_id:formData.paymentMethodId,payer:{email:formData.cardholderEmail,identification:{type:documentNumber.length===14?'CNPJ':'CPF',number:documentNumber}}});debugLog('Resposta do cartão',result);if(!result.success){setDonationStatus(result.error||'O cartão não foi aprovado.',true);return}setDonationStatus(`Doação recebida. Status: ${result.status||'em análise'}.`)}catch(error){debugLog('ERRO cartão',error);setDonationStatus('Não foi possível comunicar com o servidor de pagamentos.',true)}}
document.addEventListener('keydown',event=>{if(event.key==='Escape'){closePreview();closeFolderModal();resolveConfirmation(false)}if(event.key==='Enter'&&$('folderModal')&&!$('folderModal').classList.contains('hidden'))submitCreateFolder()});
async function exportJson(){if(!root){setStatus('Faça uma análise antes de gerar o arquivo.',true);return}setStatus('Escolha onde salvar o arquivo para IA…');debugLog('Abrindo seletor de arquivo para IA');const result=await api().export_json(root);if(result.ok)setStatus('Arquivo para IA salvo com sucesso.');else setStatus(result.error||'Geração cancelada.',true)}
window.addEventListener('pywebviewready',()=>{setViewMode('tree');loadReserved();loadDrives()});if(window.pywebview){setViewMode('tree');loadReserved();loadDrives()}
